#!/bin/env bash

# INFO: You can test the result of script using following command
# echo "4" | ./star
# INFO: pass flag -n to remove newline when using echo command
read n
# TODO: DRAW TRIANGLE HERE

for ((i=1; i<=n; i++))
do
    for ((j=1; j<=i; j++))
    do
        echo -n "*"
    done
    echo ""
done