#!/bin/env bash

# INFO: You can test the result of script using following command
# echo "Test123" | ./validasi_password
# INFO: You can validate password using regex pattern
# Example:
# match for lower alphabetic characters
# if [[ $pattern =~ [a-z] ]];
# fi

# Membaca password dari input standar (stdin)
read password

# TODO: ADD LOGIC AFTER THIS LINE
if [[ ${#password} -lt 8 ]]; then
 echo "Password terlalu pendek"
fi

if ! [[ $password =~ [A-Z] ]]; then
 echo "Password harus mengandung huruf kapital"
fi

if ! [[ $password =~ [0-9] ]]; then
 echo "Password harus mengandung angka"
fi

if [[ -z "$password" ]]; then
 echo "Password tidak boleh kosong!"
fi

#if [[ ${#password} -ge 8 &&  $password =~ [A-Z] &&  $password =~ [0-9] && !(-z "$password") ]]; then
# echo "Password diiterima"
#fi

if ! [[ -z "$password" ]]; then
    if [[ ${#password} -ge 8 &&  $password =~ [A-Z] &&  $password =~ [0-9] ]]; then
     echo "Password diterima"
    fi
fi